# Generated by Django 4.1.5 on 2023-10-09 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discounted_price',
            new_name='discount_price',
        ),
    ]
