# Generated by Django 4.1.5 on 2023-10-11 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0003_orderplace_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplace',
            old_name='status',
            new_name='state',
        ),
    ]
